# Generated by Vinkius Edge - High Performance MCP Server
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package configurations
COPY package.json package-lock.json* ./

# Install all dependencies including devDependencies for build
RUN npm ci

# Copy source code
COPY tsconfig.json ./
COPY src/ ./src/

# Compile TypeScript
RUN npm run build

# Prune devDependencies to keep final image slim
RUN npm prune --production

# -------------------------------------
# Production Image
# -------------------------------------
FROM node:20-alpine AS runner

# Enhance security by running as non-root
USER node
WORKDIR /app

# Copy minimal runtime files from builder
COPY --from=builder --chown=node:node /app/package.json ./
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/dist ./dist

# SEO & Meta attributes for Docker Hub visibility
LABEL org.opencontainers.image.title="html-markdown-converter-mcp"
LABEL org.opencontainers.image.vendor="Vinkius"
LABEL org.opencontainers.image.source="https://vinkius.com/mcp"
LABEL org.opencontainers.image.description="Vinkius Edge high-performance Model Context Protocol (MCP) server for html-markdown-converter-mcp."
LABEL org.opencontainers.image.licenses="MIT"

ENV NODE_ENV=production

# Standard entrypoint for stdio-based MCP communication
ENTRYPOINT ["node", "dist/server.js"]
